name: lsstools
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - matplotlib>=3.6.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - pyyaml>=5.4.1
  # doc
  - sphinx>=4.1.2
  - numpydoc
  - pydata-sphinx-theme
  - nbsphinx
  # test
  - pytest>=7.1.0,<8.0
  - pytest-cov>=4.1.0,<5.0
  - pytest-regressions>=2.3.0
  - pytest-datadir>=1.4.1,<2.0
  - pytest-mock
  # dev
  - black=24.1.0
  - isort
  - ipython
  - ipykernel
  - pip